jofas/jofas.github.io

src/index.html
=> Removed border and increased shadow of hero image

src/index.html, src/style.css
Enhancements:
* Fixes #1 
* Fixes #2 
* Fixes #3 
* Fixes #4 
plus style enhancements.
=> socials bar, blog and other enhancements

src/index.html
=> Hero landing height too small on horizontal mobile

src/index.html, src/style.css
=> Menu opaque if scroll position is 0

src/index.html
=> Text enhancements

src/index.html, src/style.css
=> cleanup css

static/index.html
=> passive event listeners

src/style.css
=> font-display: swap for custom font-face

static/index.html
=> images generated with mgart

static/index.html
=> fixed theme toggle

src/style.css, static/index.html
=> enhanced divider size and styling

static/index.html
=> weightlifting -> sports

static/index.html
=> enhanced intro FLOSS section

src/style.css, static/index.html
=> overflow on mobile fixed + better handling of word breaking

static/index.html
=> competencies -> skills

Makefile
=> automatically watch for file changes in static

src/style.css
I deleted all the lg related classes to make the font size smaller for large screens. Fixes #52.
=> Font size changed for large screen

static/index.html
* Fixes #56 
* Fixes #57
* Fixes #60
=> removed every occurrence of any lg:pb-* from line  232 to 646

src/style.css, static/index.html, static/theme-toggle.css
=> menus same for small and large screens

static/index.html
=> sneakily fixed layout by creating a paragraph bigger than the max width

static/index.html, static/theme-toggle.css
=> Theme toggle alignment + toggle size

static/index.html
=> enhanced wording of clean code tile

static/index.html
=> enhanced FLOSS section

static/index.html
=> CP retired
